try {
    //code test
    alert("hi everyone");
    alert(x);
    alert("bye everyone");
} catch (error) {

    //handle code
    document.write("inside catch block");
    document.write("error");
}finally{

    //always works code write here
    
    alert("bye everyone");
}